### PR TITLE
[#69] Page Header Component

### PR DESCRIPTION
**Pull request by bd-viget**
# Summary

This PR adds the Page Header Component. The basic styles have been added with plain CSS, so it's going to need some of @nathan-schmidt-viget's Tailwind love!

## Issues

* #69 

## Testing Instructions

1. Create a new page
2. Add the Page Header block

## Screenshots

Screenshot 2024-05-20 at 5 11 52 PM

Screenshot 2024-05-20 at 5 15 20 PM

### CODE REVIEW

**Comment by bd-viget** [comment]
> I think this fulfills what the Figma images show but reading the ticket, I think there's a mismatch in spec versus images?

I thought so too, but I guess I assumed the Breadcrumbs were the "menu items" and the Company Logo was the image.

Also, it's usually a bit strange to specify the links in Breadcrumbs, usually the site map decides that automatically.

**Comment by bd-viget** [comment]
@ten1seven @stephaniefois 

I think the description for ticket #69 was copied from ticket #67 and just not updated.

**Comment by bd-viget** [comment]
Ok, when testing this, you may need to run `composer install`, WP Starter now includes RankMath, which is what we're using for breadcrumbs, but they need to be enabled.

**Review by nathan-schmidt-viget — APPROVED** [review]
Works great!

**Pull request merged**
